[package]
name = "launchpad"
version = "0.1.0"
authors = ["William Gooch <william.gooch.wg@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex = "1"
midir = "0.6.1"